_target_: rfm_docking.dock.arch.DockingCSPNet
hidden_dim: 256
time_dim: 128
num_layers: 3
act_fn: silu
dis_emb: sin
num_freqs: 32
edge_style: knn
max_neighbors: 5
cutoff: 15.
ln: true
use_log_map: true  # false would put it in line with DiffCSP (euclidean distance function)
# dim_atomic_rep: ${get_dim_atomic_rep:${model.manifold_getter.atom_type_manifold}}
self_edges: false
self_cond: ${model.self_cond}
drop_be_prob: 0.5

